name: Compile and Publish Books
run-name: ${{ github.actor }} triggered the workflow
on: [pull_request]
jobs:
  build-test-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install texlive-latex-extra
      - run: pdflatex books/code/ruby/a-little-book-on-ruby-gems.latex

