name: Build, Test And Release
run-name: ${{ github.actor }} triggered the workflow
on:
  pull_request:
    [main]
jobs:
  build-test-release-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello"

